version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: meu_banco
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_labprog
